name: opeNode

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: testing
        run: |
          sudo npm i -g openode
          whereis openod

          export OPENODE_TOKEN="${{ secrets.OPENODE_TOKEN }}"
          export OPENODE_SITE_NAME="${{ secrets.OPENODE_SITE_NAME }}"

          openode ci-conf $OPENODE_TOKEN $OPENODE_SITE_NAME

          openode status
